import { KartTypeDef } from '../types';

export const KART_TYPES: KartTypeDef[] = [
  {
    id: 'cruiser',
    name: 'Cruiser Clássico',
    subtitle: 'Equilíbrio & Versatilidade',
    description: 'Kart de corrida clássico de turismo. Desempenho equilibrado ideal para qualquer tipo de circuito.',
    speed: 3,
    acceleration: 3,
    handling: 3,
    boostPower: 3,
    weight: 'Médio',
    primaryColor: '#ef4444',
    accentColor: '#ffffff',
  },
  {
    id: 'formula',
    name: 'Speed Demon F1',
    subtitle: 'Velocidade Pura em Reta',
    description: 'Chassi monolugar de fibra de carbono e ailerons aerodinâmicos. Atinge velocidades de ponta arrasadoras.',
    speed: 5,
    acceleration: 2,
    handling: 2,
    boostPower: 4,
    weight: 'Leve',
    primaryColor: '#0ea5e9',
    accentColor: '#38bdf8',
  },
  {
    id: 'offroad',
    name: 'Bumper 4x4 Off-Road',
    subtitle: 'Aceleração & Aderência Máxima',
    description: 'Suspensão reforçada e pneus todo-o-terreno largos. Arranca velozmente nas curvas e quase não perde velocidade fora de pista.',
    speed: 2,
    acceleration: 5,
    handling: 4,
    boostPower: 3,
    weight: 'Pesado',
    primaryColor: '#eab308',
    accentColor: '#1e293b',
  },
  {
    id: 'phantom',
    name: 'Drift Phantom',
    subtitle: 'Especialista em Derrapagens',
    description: 'Geometria agressiva com luz neon e turbinas auxiliares. Enche o Mini-Turbo de drift num piscar de olhos e curva com precisão cirúrgica.',
    speed: 4,
    acceleration: 3,
    handling: 5,
    boostPower: 5,
    weight: 'Leve',
    primaryColor: '#a855f7',
    accentColor: '#22d3ee',
  },
];
